on: [pull_request]

name: Build and Test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check dependencies
        run: |
          yarn install --check-cache

      - name: Prettier
        # run yarn style:fix if your PR fails here
        run: |
          yarn style:check

      - name: Build plugin
        run: |
          cd ./packages/plugins/plugin-build && \
          yarn release
      - name: Build Example
        run: |
          yarn build --ignore-cache packages/examples/lorem-ipsum/
      - name: Test
        run: |
          yarn test --ignore-cache
